app/models.py
from app import db
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash 
from . import login_manager



class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index =True)
    email = db.Column(db.String(255),unique = True,index =True)
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    bookings = db.relationship('Booking',backref = 'user', lazy = 'dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()


    def __repr__(self):
        return f'User {self.username} '



class Booking(db.Model):
    __tablename__ = 'bookings'
    id = db.Column(db.Integer,primary_key = True)
    # email = db.Column(db.String(255),unique = True,index =True)
    title =  db.Column(db.String(255))
    day = db.Column(db.String(255))
    session = db.Column(db.String(255))
    category = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

    def save_booking(self):
        db.session.add(self)
        db.session.commit()


    def __repr__(self):
        return f'Booking {self.day} '

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import Required, Email, EqualTo
from wtforms import StringField, SubmitField,RadioField,TextAreaField
from wtforms import SelectField, IntegerField

class BookingForm(FlaskForm):
    email = StringField('Enter email to recieve reciept', validators=[Required(), Email()] )
    title = SelectField('Session Type', choices=[('Music Record', 'Music Record'),('Photo Session', 'Photo Session')])
    day = SelectField('Days', choices =[('Monday','Monday'),('Tuesday','Tuesday'),('Wednesday','Wednesday'),('Thursday','Thursday'),('Friday','Friday')])
    session = SelectField('Session', choices=[('Morning Session', 'Morning Session'),('Midday Session','Midday Session'),('Evening Session','Evening Session')])
    category = SelectField('Category', choices =[('Video Record','Video Record'),('Photo Session','Photo Session'),('Music Record','Music Record')])
    submit = SubmitField('Book now')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)


    # Creating the app configurations

    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # configure UploadSet
    configure_uploads(app,photos)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # setting config
    # from .requests import configure_request
    # configure_request(app)
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User, Booking
from .forms import BookingForm,UpdateProfile
from flask_login import login_required, current_user
from .. import db,photos

@main.route('/')
# @login_required
def index():


    return render_template('index.html')


@main.route('/booking/new_booking', methods = ['GET','POST'])
@login_required
def new_booking():
    booking_form = BookingForm()
    title = 'Welcome Book with us and get the best deals in town'
    booking = Booking.query.all()


    if booking_form.validate_on_submit():
        booking = Booking(title = booking_form.title.data, day = booking_form.day.data, session = booking_form.session.data, category = booking_form.category.data)

        db.session.add(booking)
        db.session.commit()

        if booking.object.filter(user=request.user).count()> 3:
            flash('Choose another day')

        return redirect(url_for('main.new_booking'))

    

    return render_template('booking.html', booking_form = booking_form, bookings = booking, title = title, profile= profile)


@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template('profile/profile.html', user = user)

@main.route('/user/<uname>/update', methods = ['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname = user.username))

    return render_template('profile/updates.html', form = form)

@main.route('/user/<uname>/update/pic', methods = ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()

    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()

    return render_template('booking.html', booking_form = booking_form )


@main.route('/about')
# @login_required
def about():
    title = 'ABOUT US'


    return render_template('about.html', title =title)

    return redirect(url_for('main.profile', uname = uname))

app/templates/about.html
{% extends 'base.html' %}

{% block styles%} {{ super() }}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script src="https://kit.fontawesome.com/2e65670cdd.js"></script>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.js"></script>
<link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">   
<link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="node_modules/bootstrap-social/bootstrap-social.css">
<link rel="stylesheet" href="{{url_for('static',filename='css/about.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/about.css') }}">

{% endblock %}


{% block content %}
<div class="container-fluid">
    <h1> <strong> {{title}} </strong> </h1>
</div>




<div class="container-fluid">

  
    <div class="card row">
      <img src="{{ url_for('static', filename='logo.jpg')}}" alt="Chicago">
      <div class="card-body col-md-6 mx-auto">
          <h5 class="card-title" style="color: pink;">Who we are:</h5>
          <p class="card-text" >
            We are passionate and creative about the services we offer. We offer classical studio services with a friendly and skilled personel being present through all the steps you make to guide and help. Book a session with us today.
          </p>
          <a href="#prod" class="btn btn-primary">View Products</a>
          
      </div>
    </div>  
    <hr>
    <div class="row">
      <h4 style="color: pink; text-align: center;"><strong>Our Story</strong></h4>
      <div style="text-align: center; color: black;">
        <p>We take pride in offering solutions to our customers by being uniquely creative with the entire process.</p>
        <p>Award winning videos and Pictures globally are what we focus on and deliver.</p>
        <p>Our mission is to help you build a more personal connection with your audience.</p>
      </div>

    </div>
    <hr>
    <div class="row" id="prod">
      <h4 style="color: pink; text-align: center;"><strong>Our Products:</strong></h4>
      <br>
      <div class="col-md-4">
        <div class="containers">
          <img style="height: 400px; width: 100%;" src="{{ url_for('static', filename='music.jpg')}}" alt="Chicago">
  
          <div class="overlay">
            <div class="text">Music Recording</div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="containers">
          <img style="height: 400px; width: 100%;" src="{{ url_for('static', filename='vid.jpg')}}" alt="Chicago">
  
          <div class="overlay">
            <div class="text">Video Recording</div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="containers">
          <img style="height: 400px; width: 100%;" src="{{ url_for('static', filename='photo.jpg')}}" alt="Chicago">
  
          <div class="overlay">
            <div class="text">Photoshoot</div>
          </div>
        </div>
      </div>
  
  
    </div>
    





</div>


<style>
  .containers {
    position: relative;
    width: 100%;
    border: 20px;
    border-color: black;
  }
  
  .image {
    display: block;
    width: 100%;
    height: auto;
  }
  
  .overlay {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: pink;
    overflow: hidden;
    width: 0;
    height: 100%;
    transition: .5s ease;
  }
  
  .containers:hover .overlay {
    width: 100%;
  }
  
  .text {
    color: white;
    font-size: 20px;
    position: absolute;
    top: 50%;
    left: 50%;
    -webkit-transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
    white-space: nowrap;
    
  }

  .card {
  flex-direction: row;
  align-items: center;
}
.card-title {
  font-weight: bold;
}
.card img {
  width: 30%;
  border-top-right-radius: 0;
  border-bottom-left-radius: calc(0.25rem - 1px);
}
@media only screen and (max-width: 768px) {
  a {
    display: none;
  }
  .card-body {
    padding: 0.5em 1.2em;
    margin-top: 25%;
    padding-top: 25%;
    border-top: 25%;

  }
  .card-body .card-text {
    margin: 0;
  }
  .card img {
    width: 50%;
  }
}
@media only screen and (max-width: 1200px) {
  .card img {
    width: 40%;
  }
}
  </style>
  

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/booking.css') }}">

</head>
<body>

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}




    {% block content %}  {% endblock %}
    




<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
</body>
</html>

app/templates/booking.html
{% extends 'base.html' %} 

{% import 'bootstrap/wtf.html' as wtf %}
<body style="    background-image: url('https://images.unsplash.com/photo-1584213610817-948feb8c633a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80'); background-size:cover; background-repeat: no-repeat;
">

    {% block content %}
<div class="container-fluid" >
<div class="container-fluid" style="color: rgb(243, 200, 9);" >
    <div class="row">
        <h1> {{title}} </h1>
        <div class="col-md-6" style="color:black;" >
            {{wtf.quick_form(booking_form)}}



        </div>
        <div class="col-md-6">
            {% for booking in bookings %}
            <h2>Booking</h2>
            <p> {{booking.email}} </p>
            <p> {{booking.title}} </p>
            <p> {{booking.day}} </p>
            <p> {{booking.session}} </p>
            <p> {{booking.category}} </p>
            {% endfor %}
        </div>
    </div>
  </div>
</div>

{% endblock %}
    
</body>

app/templates/index.html
{% extends 'base.html' %}

{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/profile.css')}}">
<!-- <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}"> -->
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script src="https://kit.fontawesome.com/2e65670cdd.js"></script>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.js"></script>
<link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">   
<link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="node_modules/bootstrap-social/bootstrap-social.css">

{% endblock %}


{% block content %}
<div class="container-fluid">
    <h1> <strong> {{title}} </strong> </h1>
   
</div>

<div class="container-fluid">

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
        
            <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img style="height: 400px; width: 100%;" src="{{ url_for('static', filename='la.jpg')}}" alt="Los Angeles">
            
                <div class="carousel-caption" style="color: black;">
                    <h3>Photo sessions</h3>
                    <p>Camera flashes lights always so much fun!</p>
                </div>
            
            </div>
        
            <div class="item">
                <img style="height: 400px; width: 100%;" src="{{ url_for('static', filename='chicago.jpg')}}" alt="Chicago">
            
                <div class="carousel-caption">
                    <h3>Studio</h3>
                    <p>Believe in us and we'll make you shine</p>
                </div>
            
            </div>
        
            <div class="item">
                <img style="height: 400px; width: 100%;" src="{{ url_for('static', filename='ny.jpg')}}" alt="New York">
            
                <div class="carousel-caption">
                    <h3>Video Recordings</h3>
                    <p>We help you explore what is around the corner</p>
                </div>
            
            </div>

            <div class="item">
                <img style="height: 400px; width: 100%;" src="{{ url_for('static', filename='outdoor.jpg')}}" alt="New York">
            
                <div class="carousel-caption">
                    <h3>Outdoor</h3>
                    <p>We also do outdoor sessions. Don't have one in mind?we know a few you will love.</p>
                </div>
            
            </div>

            <div class="item">
                <img style="height: 400px; width: 100%;" src="{{ url_for('static', filename='wedding.jpg')}}" alt="New York">
            
                <div class="carousel-caption">
                    <h3>Milestones</h3>
                    <p>We are here to capture all those milestones you make.</p>
                </div>
            
            </div>

            <div class="item">
                <img style="width: 100%; height: 400px;" src="{{ url_for('static', filename='traditional.jpg')}}" alt="New York">
            
                <div class="carousel-caption">
                    <h3>Groups</h3>
                    <p>We have a special offer for groups of more than 8. Fun!</p>
                </div>
            
            </div>

            <div class="item">
                <img style="height: 400px; width: 100%;" src="{{ url_for('static', filename='team.jpg')}}" alt="New York">
            
                <div class="carousel-caption">
                    <h3>Live recordings</h3>
                    <p>We got you and or your team throughout all the steps of the way. Book us today.</p>
                </div>
            
            </div>

            <div class="item">
                <img style="height: 400px; width: 100%;" src="{{ url_for('static', filename='couple.jpg')}}" alt="New York">
            
                <div class="carousel-caption">
                    <h3>Couples' Special</h3>
                    <p>Come with your significant other and crash those couple goals</p>
                </div>
            
            </div>
            <div class="item">
                <img style="width: 100%; height: 400px;" src="{{ url_for('static', filename='recreate.jpg')}}" alt="New York">
            
                <div class="carousel-caption" style="color: black;">
                    <h3>Creativity</h3>
                    <p>We have creative partners who can recreate our studios into anything you have in mind. </p>
                </div>
            
            </div>

        </div>
        
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
            </a>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6">
                <div class="card text-center">
                    <div class="card-header">
                    Featured
                    </div>
                    <div class="card-body">
                    <h5 class="card-title" style="color: green;"><span>Special Offer.</span></h5>
                    <p class="card-text">On offer this week is a free fully styled interview room. Its time to get that podcast started. The world is full of music. Listen.</p>
                    <a href="#" class="btn btn-primary">Book a session now</a>
                    </div>
                    <div class="card-footer text-muted" style="color: red;">
                    2 days ago
                    </div>
                    <video width="320" height="240" controls>
                        <source src="{{ url_for('static', filename='studio.mov')}}" type="video/mp4">
                        <source src="movie.ogg" type="video/ogg">
                        Your browser does not support the video tag.
                      </video>
        
                </div>
            </div>

            <div class="col-md-6">
                <div class="container">
                <img class="smart" style="width: 50%; height: 400px;" src="{{ url_for('static', filename='smart.jpg')}}" alt="New York">
                </div>
            </div>
              
        </div>
        <hr>
</div>



  <!-- Footer -->
  <footer>
    
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="copyright text-muted">Copyright &copy; RFSTUDIOS.2021</li>
            <li class="list-inline-item">
              <a href="https://facebook.com/OscarGichana9" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.instagram.com/ossy_gichy/" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://github.com/OscarGichana" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" style="color: pink;" href="/"> RF STUDIO </a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a class="fa fa-home fa-lg" href="/">Home</a></span></li>
          <li><a class="fa fa-about fa-lg" href="/about">About Us</a></span></li>

          {% if current_user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link fa fa-user" href="{{url_for('main.profile',uname=current_user.username)  }}  ">{{current_user.username}}</a>
          </li>

          <li class="nav-item">
            <a class="nav-link fa fa-clock-o" href="{{url_for('main.new_booking') }}  ">BOOK A SESSION</a>
          </li>


          <li class="nav-item">
            <a class="nav-link fa fa-sign-out" href="{{url_for('auth.logout')}}  ">Sign Out</a>
          </li>

          {% else %}

          <li class="nav-item">              
            <a class="nav-link fa fa-sign-in" href="{{url_for('auth.login')}}">Sign In</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link fa fa-registered" href="{{url_for('auth.register')}}">Sign Up</a>
          </li> -->
          {% endif %}

        </ul>
      

      </div>

  </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container-fluid">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} Studio </p>
    {% endif %}
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="Avatar" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}

    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/updates.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}